name: Events Demo 1
on: 
  pull_request:
      # Activity Types 
      # types can be specified in a square bracket if there more than one activity being tracked.
      # types: [opened, edited]
      # types can be specified continious list of activity if there one or more.
      types: 
        - opened
        # - edited      
      branches:
        # main
        - main
        # dev-new or dev-this-is-new
        - 'dev-*'
        # feat/new or feat/new/button etc.,
        - 'feat/**' 
  workflow_dispatch:
  push:
    branches:
      # main
      - main
      # dev-new or dev-this-is-new
      - 'dev-*'
      # feat/new or feat/new/button etc.,
      - 'feat/**' 
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."